### ISSUE TITLE
incompatible with ipython 0.11

### ISSUE THREAD

**Issue by juliantaylor** [enthought/envisage#1]
envisage/plugins/ipython_shell/view/ipython_shell_view.py uses the old ipython api:

```
line 9: from IPython.kernel.core.interpreter import Interpreter
```

IPython.kernel has been replaced by IPython.parallel in ipython 0.11.
Unfortunately Interpreter class does not exist anymore and I don't know with what it was replaced.

**Comment by mdickinson** [comment]
Closing as out of date.
