### ISSUE TITLE
single_project plugin uses deprecated adaptation machinery

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#124]
The `single_project` plugin uses the outdated and deprecated `adapts` machinery. which will be removed in Traits 5.0.0. The code should be updated to use the newer adaptation patterns.

**Comment by mdickinson** [comment]
Code link: https://github.com/enthought/envisage/blob/f14c2d1ab95677a7ccc63667757c1bf44c852602/envisage/ui/single_project/view/project_view.py#L19

**Comment by RobinD42** [comment]
I've just run into this after updating a project's dependencies pulled in the new traits.

**Comment by mdickinson** [comment]
@RobinD42 Can you elaborate? Are you using the `single_project` plugin? I was assuming that no-one was using it.

**Comment by RobinD42** [comment]
Yep, it's being used in the encad project, in `encad/model/project/cad_project.py`. I've not yet dug into that part of the code to get to know it better, I was just trying to build the devenv and run the application and ran into the traceback when project_view tries to import adapts.

**Comment by mdickinson** [comment]
Thanks; marking this as a bug.

**Comment by mdickinson** [comment]
@RobinD42 What would be the impact of getting rid of the `single_project` plugin on your work? It looks to me as though it was added to Envisage in half-baked state and never finished: there are imports that refer to modules that don't exist, for example, and I'm not all that keen on putting work into it if it's not being used.

**Comment by mdickinson** [comment]
As noted by @jwiggins on Slack:

> Correction: `apptools.logger.agent.attachments` references it as well

Code link: https://github.com/enthought/apptools/blob/30cd14d57e18f805d15af166039eafdc3bc8fe3c/apptools/logger/agent/attachments.py#L43-L50

What's confusing about this one is that the id that's being used to retrieve the `ModelService` doesn't match the id currently used by Envisage, so it's not clear how this `apptools` code would have worked (or indeed whether it ever did).

**Comment by RobinD42** [comment]
> @RobinD42 What would be the impact of getting rid of the single_project plugin on your work?

It's unclear to me at the moment since my primary purpose currently is to get things working with Python3 and I haven't paid much attention to actual functionality yet. The single_project things being imported and used are: `envisage.ui.single_project.api.Project` and `envisage.single_project.services`.
