### ISSUE TITLE
Document extra dependencies

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#126]
The `envisage` package makes use of a number of packages that aren't listed as dependencies on the pypi package (https://github.com/enthought/envisage/blob/f14c2d1ab95677a7ccc63667757c1bf44c852602/envisage/__init__.py#L6-L9). This is because only `apptools` and `traits` are dependencies of the core envisage package.

Other dependencies such as `ipykernel`, `pyface`, `tornado`, `traitsui` etc are extra dependencies which need to be installed to make full use of the envisage package.

In the future, we might want to make use of the `extras_require` keyword in `setup.py`.

**Comment by mdickinson** [comment]
#139 added 'apptools' to the list of dependencies in the README
