### ISSUE TITLE
Fix/update docs

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#127]
- [ ] fix warnings when building docs
- [x] fix navigation in docs
- [x] update docs to use enthought sphinx theme

**Comment by aaronayres35** [comment]
I believe the third bullet has been resolved by #157

**Comment by aaronayres35** [comment]
Also #290 updates to "newest" (unsure if thats still true) Enthought Sphinx Theme, and says in the description it "fixes search functionality".  I have not tested, so I will not mark the second as complete, but it seems it very well may be solved already.
  
I did however build the docs earlier and I remember still seeing some warnings.

**Comment by aaronayres35** [comment]
Currently the only warning I see when building docs is:
```
/Users/aayres/Desktop/envisage/docs/source/envisage_core_documentation/message_of_the_day_(using_eggs).rst: WARNING: document isn't included in any toctree
```
Im not exactly sure what we want to do with this.  

Also, I tested navigation/search on the built docs and saw no problems so I believe that that is fixed.  

@rahulporuri any suggestions on the remaining warning?  Once that is addressed I believe this issue can be closed

**Comment by rahulporuri** [comment]
If it's only a question of that document not being included in any toctree, I think we can close this issue. I'm not entirely sure how up-to-date that document even is in the first place.

**Comment by aaronayres35** [comment]
Closing based on the above
