### ISSUE TITLE
String repr for ExtensionPoint instances

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#141]
Currently `ExtensionPoint` reprs use the standard Python repr i.e. `'<envisage.extension_point.ExtensionPoint object at 0x7f125d4ce550>'`, which is not useful in anyway. It would be nice if `__str__` returns the `ExtensionPoint.id` attribute.

**Comment by corranwebster** [comment]
I think I would have a preference for something like `ExtensionPoint(id='foo.bar')` - although this is better for `repr` than `str`.  Is there a particular use-case you had for overriding `__str__`?

**Comment by rahulporuri** [comment]
I'd also prefer overriding `__repr__` and using it as `__str__` but I wasn't sure what a good repr would be. I'll update the PR based on your comments.
