### ISSUE TITLE
Setting always_use_default_layout will never use the default layout if there is an application_memento file

### ISSUE THREAD

**Issue by jjenthought** [enthought/envisage#143]
Setting `self.always_use_default_layout=True` seems like it should use the default layout specified and not load the previous state. However, the opposite behaviour happens in practice.

The problem seems to be that in `create_windows` the `restore` argument is `restore=self.always_use_default_layout`, but it should be `restore=not self.always_use_default_layout` as setting `restore=True` means `self._restore_layout_from_state` gets called, restoring things from a previous state and not using the default layout as requested.

**Comment by corranwebster** [comment]
This seems like a simple fix - do you have time to put together a PR?

**Comment by jjenthought** [comment]
Sure, I'll put something together!

**Comment by jjenthought** [comment]
Closed by #144
