### ISSUE TITLE
Remove envisage.categories extension point

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#180]
A future version of Traits is likely to remove support for categories. At that point, we should remove the `envisage.categories` extension point from the core plugin.

This should likely be part of a post-2019 Python 3-only Envisage release, with a major version number bump.

**Comment by rahulporuri** [comment]
Note that the `Category` trait has been removed from traits master . See PR - https://github.com/enthought/traits/pull/568 . We're already seeing the envisage cron job fail.
