### ISSUE TITLE
Replace _compat file and its usage with six

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#191]
See file here - https://github.com/enthought/envisage/blob/master/envisage/_compat.py , which essentially redefines functionality currently available in six.

**Comment by rahulporuri** [comment]
We're holding off on this issue until the first Python 3-only release, after Jan 1 2020.

**Comment by mdickinson** [comment]
The master branch is now aimed at that Python-3-only release, so PRs are welcome.

**Comment by rahulporuri** [comment]
fixed in #262
