### ISSUE TITLE
Broken code coverage badge on PyPI

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#215]
From the [Envisage 4.8.0 page](https://pypi.org/project/envisage/4.8.0/) on PyPI:

![Screenshot 2019-09-16 at 09 03 11](https://user-images.githubusercontent.com/662003/64942413-e0b61480-d860-11e9-9759-9edcaaa3b035.png)

**Comment by mdickinson** [comment]
The relevant piece of the source on the PyPI page looks like this:
```

<a href="https://travis-ci.org/enthought/envisage" rel=nofollow><img alt="Build Status" src="https://warehouse-camo.cmh1.psfhosted.org/b798113cae65ca1a6deeb3addb4b5a34ae124cf7/68747470733a2f2f7472617669732d63692e6f72672f656e74686f756768742f656e7669736167652e706e67"></a>
--
  | <a href="http://codecov.io/github/enthought/envisage?branch=master" rel=nofollow><img alt="http://codecov.io/github/enthought/envisage/coverage.svg?branch=master" src="https://warehouse-camo.cmh1.psfhosted.org/dd376d459848d895c310813c2569ae7e043544b8/687474703a2f2f636f6465636f762e696f2f6769746875622f656e74686f756768742f656e7669736167652f636f7665726167652e7376673f6272616e63683d6d6173746572"></a>

```

**Comment by mdickinson** [comment]
Possibly we should just remove the coverage badge. It's not like the number on it is something to be proud of right now. :-)

**Comment by rahulporuri** [comment]
The only thing i could figure out is - traits, traitsui and pyface have working badges which use https and envisage has a broken badge which uses  http.

**Comment by mdickinson** [comment]
Well, in that case #216 *may* actually fix this.

**Comment by mdickinson** [comment]
Looks like #216 *did* fix this. Here's what I see with the 4.9.0 release.

![Screenshot 2019-11-19 at 11 24 44](https://user-images.githubusercontent.com/662003/69142681-35734700-0abf-11ea-9b40-8fc8ef7b7446.png)

**Comment by mdickinson** [comment]
(Not that that "54%" is something to be proud of, but still ...)
