### ISSUE TITLE
Consider deprecating/remove the TwistedApplication

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#247]
The [TwistedApplication](https://github.com/enthought/envisage/blob/master/envisage/twisted_application.py) seems to have been an experiment which lives on the master branch. There are no tests that I can find for it.

We might want to deprecate and remove it from the codebase.

Note that if the module gets removed, we will also need to remove it from the `envisage.api`.

**Comment by mdickinson** [comment]
+1 for removal. It's an interesting idea, but not something that we want to be maintaining. (And the existing code is so small that it's trivial to reproduce.)

**Comment by mdickinson** [comment]
> We might want to deprecate and remove it from the codebase.

Just remove it. Without evidence of users, I don't think there's any value in deprecation here.
