### ISSUE TITLE
Get flake8 running on the codebase

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#266]
For the 5.0 release, I'd like to get flake8 running on the codebase, in the same way as we're already doing for Traits.

At the last count, the number of individual complaints from `flake8` was almost 3000:
```
mirzakhani:envisage mdickinson$ flake8 . | wc -l
    2825
```

So this looks like a daunting task.

However, I think we can approach this incrementally: start by adding a `setup.cfg` with a list of flake8 warnings and errors to ignore (and while we're at it, exclude the `examples` directory). Add warnings and errors to the ignore list until nothing is reported. Now remove the more serious warnings and errors from the list, one at a time, fixing up the code to comply as we go.

The most important errors and warnings are the ones that are likely to catch future bugs: syntax errors, unused names, undefined names, unused imports, and the like.

For spacing errors, I'd recommend that we do a one-time application of black to the codebase.

**Comment by mdickinson** [comment]
> At the last count, the number of individual complaints from `flake8` was almost 3000:

#267 reduces the number from 2825 to 863.

**Comment by mdickinson** [comment]
See #268 for the machinery.

Just for fun, here's a breakdown of the current warnings on master:
```
mirzakhani:envisage mdickinson$ flake8 . --format="%(code)s" | sort | uniq -c | sort -r
 543 E266
 169 F401
  66 E501
  17 F821
  15 E722
  11 E231
   9 E401
   6 F841
   5 W605
   4 E203
   3 W601
   3 E713
   3 E402
   2 E741
   2 E302
   2 E251
   1 F403
   1 E731
   1 E721
```

**Comment by kitchoi** [comment]
So flake8 is already running on CI, I saw that there are some ignores in the setup.cfg.

Trying to understand what needs to happen in order to close this issue: I am not sure an empty setup.cfg is what we are shooting for here. I am not sure if `examples` is meant to stay there. `*/api.py:F401` probably should stay.

**Comment by rahulporuri** [comment]
I think this issue can be closed @kitchoi . The examples which we will be including in `envisage` can be flake8-d once we move them into the package and `envisage.ui.single_project` has been deprecated and is meant to be removed - so there is no use flake8-ing it.

closing issue.

**Comment by mdickinson** [comment]
Yes, sorry; this should have been closed when #268 was merged.

**Comment by kitchoi** [comment]
I see. Thank you.
I have started flaking `envisage/ui/single_project` a bit. I will try to push something meaningful for what I have got so far.

**Comment by mdickinson** [comment]
I'm not sure it's worth it; unless there's a strong reason to keep it, I'd recommend that we just delete `single_project`.

**Comment by kitchoi** [comment]
Yeah as soon as I started looking into it, I found some dead code and issues about deleting it, but there are also some light uses of it. I just what is cheap to do.

**Comment by rahulporuri** [comment]
i've opened https://github.com/enthought/envisage/issues/327 to discuss removing `envisage.ui.single_project`.
