### ISSUE TITLE
Remove ipykernel Heartbeat patch when updating to ipykernel version >5

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#298]
The ipykernel `Heartbeat` was been patched earlier and the patch isn't needed when we update to a new version of ipykernel > 5.x.

The patched `Heartbeat` is used by the `IPKernelApp`, which can also be removed

https://github.com/enthought/envisage/blob/1eccd8074c1bc0661b64fba287cc88add446ada4/envisage/plugins/ipython_kernel/kernelapp.py#L38-L58

https://github.com/enthought/envisage/blob/master/envisage/plugins/ipython_kernel/heartbeat.py

**Comment by rahulporuri** [comment]
FTR

- the patch was introduced in the envisage PR https://github.com/enthought/envisage/pull/188
- the upstream issue is https://github.com/ipython/ipykernel/issues/430 
- the upstream fix is https://github.com/ipython/ipykernel/pull/431, which has been available and is available in v 5.3.4 of ipykernel

**Comment by mdickinson** [comment]
Closing: IPython components have been removed from Envisage.
