### ISSUE TITLE
Is an envisage.plugins.api useful?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#306]
At the moments, applications built using Envisage e.g. `Application` or `TasksApplication` applications which want to use plugins defined in envisage need to import the plugins directly from the plugin files e.g. `envisage.plugins.ipython_kernel.ipython_kernel_plugin.IPythonKernelPlugin`.

Instead, it might be useful to add an `envisage.plugins.api` module which re-exports some of the plugins defined in `envisage.plugins`. Based on anecdotal knowledge of plugin usage, the `api` module can start out as 

```
from envisage.plugins.event_manager.plugin import EventManagerPlugin

from envisage.plugins.ipython_kernel.actions import StartQtConsoleAction
from envisage.plugins.ipython_kernel.internal_ipkernel import InternalIPKernel
from envisage.plugins.ipython_kernel.ipython_kernel_plugin import IPythonKernelPlugin, IPYTHON_KERNEL_PROTOCOL
from envisage.plugins.ipython_kernel.ipython_kernel_ui_plugin import IPythonKernelUIPlugin
```

**Comment by rkern** [comment]
`envisage.plugins` is more of a place to put various plugins, not something with a coherent API itself. Each plugin subpackage under it could and should provide an `api.py`, though.

**Comment by rahulporuri** [comment]
looks like the action here is to create and fill the relevant api modules.

```
envisage.plugins.event_manager.api
envisage.plugins.ipython_kernel.api
```
