### ISSUE TITLE
Remove IPythonKernelPlugin.init_ipkernel flag

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#309]
The `init_ipkernel` boolean flag was introduced on the `IPythonKernelPlugin` for backwards compatibility in the PR https://github.com/enthought/envisage/pull/227. The PR also introduced a deprecation warning stating that in the future, the kernel will be initialized at plugin start time and that the flag can be set to `True` to enable future behavior now.

The changes were available to end users starting with Envisage v 4.9.0. For the upcoming 5.0.0 release, we should be able to remove the flag, the deprecation warning and initialize the kernel unconditionally at plugin start time.

https://github.com/enthought/envisage/blob/ae477a4e4919681006c9e84bb4f9edb77b65bba8/envisage/plugins/ipython_kernel/ipython_kernel_plugin.py#L67-L72

**Comment by mdickinson** [comment]
I'm a little bit nervous about removing this so soon after it was introduced. Are we sure that everyone we care about has already upgraded to 4.9.0, and dealt with the `DeprecationWarning`s?

I'd propose not removing this until the 6.0 release.

**Comment by rahulporuri** [comment]
removing from from 5.0.0 milestone.

**Comment by kitchoi** [comment]
The deprecation warning also instructs user to instantiate the plugin like this `IPythonKernelPlugin(init_ipkernel=True)`.
So for this reason, the trait cannot be removed.
If we really really want to remove the trait, its default needs to be changed, and another round of deprecation warning to wane off setting the trait altogether...

**Comment by mdickinson** [comment]
Closing: IPython components have been removed from Envisage.
