### ISSUE TITLE
Remove support for passing `gui_backend` kwarg to `InternalIPKernel.init_ipkernel`?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#310]
The `gui_backend` kwarg was deprecated on the `InternalIPKernel.init_ipkernel` method in the PR https://github.com/enthought/envisage/pull/227. The PR also introduced a deprecation warning stating that in the future, passing `gui_backend` might result in an error.

The changes were available to end users starting with Envisage v 4.9.0. For the upcoming 5.0.0 release, we might want to remove the kwarg and the deprecation warning.

https://github.com/enthought/envisage/blob/ae477a4e4919681006c9e84bb4f9edb77b65bba8/envisage/plugins/ipython_kernel/internal_ipkernel.py#L91-L100

**Comment by mdickinson** [comment]
I think it may be too soon to consider removing this. We probably want to keep it around until Envisage 6.0 (unfortunately).

**Comment by rahulporuri** [comment]
removing from envisage 5.0.0 milestone.

**Comment by mdickinson** [comment]
Closing: IPython components have been removed from Envisage.
