### ISSUE TITLE
Improve API docs : document traits.

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#314]
The API documentation for important classes like `Application` don't have traits documented automatically because the comment strings don't use the expected `#:`. They just use `#`. https://docs.enthought.com/envisage/api/envisage.html#module-envisage.application

https://github.com/enthought/envisage/blob/ae477a4e4919681006c9e84bb4f9edb77b65bba8/envisage/application.py#L50-L56

Addressing this issue has the additional reward that other projects can link to traits on envisage classes, specifically to traits defined on classes using intersphinx.

Every single class in envisage does not need to be fixed but all of the important classes that applications built using envisage need their traits documented. A non-exhaustive list of such classes is 

- `Application` and `IApplication`
- `TasksApplication`, `TaskFactory`, `TaskExtension`
- `Plugin`, `CorePlugin` and `IPlugin`
- `PluginManager` and `IPluginManager`
- `ServiceOffer`

**Comment by aaronayres35** [comment]
Can we close #303 as it is now just a sub-issue of this issue?

**Comment by rahulporuri** [comment]
thanks @aaronayres35 . closed the duplicate/sub-issue.
