### ISSUE TITLE
Consider contributing a few examples to etsdemo.

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#320]
For the 5.0.0 release, it might be good to contribute a few of the example envisage applications to the etsdemo application. The following examples work as expected and make for a good start : 

- hello world.
- MOTD.
- tasks attractors.

**Comment by kitchoi** [comment]
Some of these examples assume a specific Python Path when they are run.
Some of them have side-effect of creating a log file in the current directory where they are run.
I am not sure etsdemo is mature enough to handle all these... it might need a bit more investigation to scope.

**Comment by rahulporuri** [comment]
I think it's perfectly understadable to update/modify the existing envisage examples to suit the way etsdemo works.

**Comment by kitchoi** [comment]
Actually I think it is probably better to change the examples such that it can be run from anywhere: It makes etsdemo optional, and anyone can run the examples even without the demo application.

We should get rid of the side-effect of logging to a file: it is quite annoying to run an example and realize it has left behind a file.

**Comment by kitchoi** [comment]
After #377, #379, we are left with these actions (I think):

- Remove logging to a file side-effect in examples. They are not particularly useful and is unexpected.
- Move the examples into `envisage`, make sure they are distributed as package data, and add an entry point.
