### ISSUE TITLE
Use `traits.util.import_symbol` instead of `ImportManager` in envisage

### ISSUE THREAD

**Issue by pberkes** [enthought/envisage#33]
We have implementations of importing a symbol from a string scattered all over ETS. The current implementation in `traits.util.import_symbol` is recent, and handles both the new way of specifying symbols (`tarfile:TarFile.open'`) and the old, frowned-upon way of doing it (`'tarfile.TarFile.open'`).

**Comment by mdickinson** [comment]
Closing this. `traits.util.import_symbol` is something that we'd like _fewer_ 3rd party uses of, rather than more. It's something that never really belonged in Traits in the first place, and may be removed at some point in the future.
