### ISSUE TITLE
Create and fill remaining plugin subpackage api modules

### ISSUE THREAD

**Issue by aaronayres35** [enthought/envisage#333]
In #323 `envisage.plugins.event_manager.api` was created and populated with `EventManagerPlugin`. Likewise `envisage.plugins.ipython_kernel.api` was added to and re-exports `IPythonKernelPlugin`, `IPythonKernelUIPlugin`, and more.

However, the existing `envisage.plugins.python_shell.api` module currently only contains : `from .i_python_shell import IPythonShell`.  Should we also include `PythonShellPlugin` there?  It would make sense to follow the pattern of the other plugin apis.

Similarly we currently have https://github.com/enthought/envisage/blob/master/envisage/plugins/text_editor/api.py which does not re-export `TextEditorPlugin`, and also https://github.com/enthought/envisage/tree/master/envisage/plugins/tasks
which does not have an `api` to export `EnvisagePythonShellTask` and `PythonShellPlugin`.

#323 likely should have included all these updates to fully fix #306.

**Comment by rahulporuri** [comment]
no i think this is overkill. we rerely use anything from `envisage.plugins.python_shell.*` or from `envisage.plugins.text_editor.*` so adding and maintaining api modules for them is overkill.

**Comment by aaronayres35** [comment]
Closing based on the above comment
