### ISSUE TITLE
Experiment with aws cpu and and virtualization in travis CI

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#350]
ref : https://blog.travis-ci.com/2020-09-11-arm-on-aws

There is a new type of CPI available on travis CI com and a new type of virtualization - both of these put together apparently provide a meaningful speedup in travis-ci.com CI jobs. Now that envisage CI has been moved over from travis-ci.org to travis-ci.com, we can experiment with these variables to see if we see a meaningful speedup.

**Comment by mdickinson** [comment]
Closing: we've migrated all CI to GitHub Actions, so this is no longer relevant.
