### ISSUE TITLE
ExtensionPointChangedEvent `__repr__` says it was a TraitListEvent

### ISSUE THREAD

**Issue by kitchoi** [enthought/envisage#352]
Since Traits 6.1, `TraitListEvent` has its `__repr__` implemented. Envisage has an `ExtensionPointChangedEvent` that merely subclasses `TraitListEvent` to add an extension point id, and it does not reimplement the `__repr__`. 

Consequently, when printing an instance of `ExtensionPointChangedEvent`, one may then think they are handling a `TraitListEvent`.

```
>>> print(event, type(event))
TraitListEvent(index=None, removed=[], added=[42, 'a string', True]) <class 'envisage.extension_point_changed_event.ExtensionPointChangedEvent'>
```

Reimplementing `__repr__` for `ExtensionPointChangedEvent` should fix this.

**Comment by mdickinson** [comment]
This sort of thing is the main reason to use `self.__class__` in the `__repr__` instead of hard-coding the type name. We should update the Traits code at https://github.com/enthought/traits/blob/786a39ee9a94f925e10a602b84fdc17b1895816a/traits/trait_list_object.py#L57 to do that.
