### ISSUE TITLE
Remove old examples

### ISSUE THREAD

**Issue by kitchoi** [enthought/envisage#381]
The following examples look like they are so outdated that they are either not useful or they are advertising practices we don't want to encourage anymore:

- examples/MOTD_Using_Eggs
   See #329 also
   It demonstrates building an envisage application and packaging it up into distributed egg. The part to do with building an envisage application is already covered by `examples/MOTD`. To part to do with packaging it up into a distributed egg uses `bdist_egg`, which is a machinery not many of us use nowadays.
- examples/plugins/workbench
   These examples uses `workbench`, which is deprecated (somewhere I remember seeing deprecation warning... maybe emitted from pyface.)
- examples/plugins/tasks/ipython_kernel
    The main feature does not seem to be working. See #330.

**Comment by kitchoi** [comment]
Note that there exists documentation for `MOTD_Using_Eggs`, but that documentation has not been live (at least for sometime). When building the documentation, one sees the following warning:
```
docs/source/envisage_core_documentation/message_of_the_day_(using_eggs).rst: WARNING: document isn't included in any toctree
```

**Comment by kitchoi** [comment]
The ipython_kernel example is only half working: https://github.com/enthought/envisage/issues/330

The part to do with showing a directory and editing a python file is fine, but the IPython console is not working at least when I tested it today with PySide2 5.15.2. Supposedly the example's purpose is to demonstrate the capability of integrating with IPython kernel, not having a working IPython console is a showstopper and we might want to delete the example so that it is less visible and resurrect it some later time.

**Comment by kitchoi** [comment]
There are plans to move workbench out for it to die with respect (i.e. any projects that still need it can use it at their own risk). Then the examples in `examples/plugins/workbench` are useful to help us understand how workbench is supposed to be used (as tests don't exist). Those examples could go with the move of workbench.

**Comment by mdickinson** [comment]
#557 removes most of these, but keeps one workbench-based example. We haven't yet managed to officially deprecate workbench.
