### ISSUE TITLE
Rebuild documentation to fix broken links to GitHub

### ISSUE THREAD

**Issue by kitchoi** [enthought/envisage#382]
#380 move some example files from `examples` to `envisage/examples`. Some of them are linked from the live documentation and therefore the move will result in broken links. The documentation should be rebuilt to fix those links.

Release 5.0.0 is happening soon so this issue may be closed after the release, which will also rebuild the documentation (see #373). However the broken link issue is orthogonal to the release.

**Comment by aaronayres35** [comment]
I believe this can be closed.  With the current docs the links seem to work:
see https://docs.enthought.com/envisage/envisage_core_documentation/introduction.html and click on `Hello World` in the last paragraph. (I checked other links as well and all looks correct AFAICT)

see PRs #379 #380 and #386
