### ISSUE TITLE
Envisage contributions to etsdemo dont work as expected.

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#389]
The recent release of envisage (5.0.0) contributes examples to the etsdemo application but the examples don't work as expected from the etsdemo app. I am able to see and browse through the examples in the etsdemo application but clicking "Run" does nothing - there are no tracebacks on the command line, there are no errors in the application output.

**Comment by rahulporuri** [comment]
Note that I was initially missing dependencies (specifically, mayavi, chaco and scipy for the tasks attractors example) but I was hoping that'd be communicated in the GUI or on the command line somehow.

I installed the missing packages - and the examples still don't work/run as expected.

**Comment by kitchoi** [comment]
It is directly this issue: https://github.com/enthought/traitsui/issues/1428

I don't think the examples in envisage should change. Instead, the demo app should change. Shall we close this issue here?

**Comment by rahulporuri** [comment]
I totally forgot. Closing.
