### ISSUE TITLE
Need test eggs for python 3.10

### ISSUE THREAD

**Issue by opoplawski** [enthought/envisage#396]
Fedora is preparing for python 3.10 (see https://bugzilla.redhat.com/show_bug.cgi?id=1922975) so we need test eggs for 3.10, just like we did for 3.9 (#286 #289).  There was some mention previously about moving away from the pre-built eggs or making the tests optional.  That sounds like a good idea.

Thanks!

**Comment by opoplawski** [comment]
Python 3.10.0 beta 2 has now landed in Fedora Rawhide and so this package now fails to build there.  Can this be addressed soon?  Thanks.

**Comment by hroncok** [comment]
For reference, I think we can generate those eggs in Fedora, when we build the package: https://src.fedoraproject.org/rpms/python-envisage/pull-request/2

**Comment by mdickinson** [comment]
Thanks for the ping. This should be a quick fix. I'll aim to get to it in the next couple of days.
