### ISSUE TITLE
Remove contributes_to decorator and related functionality

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#399]
Update : I have updated this issue to reflect the decision we have come to - that the `contributes_to` decorator and the related functionality seen below shall be removed. Once this code is removed, we will be making a new major release of `envisage` - version `6.0.0`. Along with removing the code, there are tests and an example/docstring in apptools that will need to be updated. This decision has been taken because we could not find any code that made use of the `@contributes_to` decorator.

Along with removing the `@contributes_to` decorator, the codepaths which handled `enthought.` + extension point id namespace for extension points will also be removed. This was backwards compatibility code - which no longer seems relevant.

Ref https://github.com/enthought/envisage/blob/d62af08e75c5555e69c4fc4688393dee737680e8/envisage/extension_point.py#L27

Original issue : 

`Plugin.get_extensions` checks for the presence of traits that use the metadata `contributes_to=extension_point_id`. If no such traits are discovered, the code tries to discover methods which are decorated with [`contributes_to`](https://github.com/enthought/envisage/blob/d62af08e75c5555e69c4fc4688393dee737680e8/envisage/extension_point.py#L27-L65). `Plugin._harvest_methods` is used for this discovery.

`Plugin._harvest_methods` can be sped up to make application startup quicker.

https://github.com/enthought/envisage/blob/d62af08e75c5555e69c4fc4688393dee737680e8/envisage/plugin.py#L142-L153
https://github.com/enthought/envisage/blob/d62af08e75c5555e69c4fc4688393dee737680e8/envisage/plugin.py#L375-L391

<details><summary>script to profile envisage application</summary>

```
"""
run $ python test_package\main.py
"""
import cProfile
profile = cProfile.Profile()
profile.enable()

from envisage.api import Application, ExtensionPoint, Plugin, PluginManager
from traits.api import Any


class DefinesExtPt(Plugin):

    ext_pt = ExtensionPoint(id="magic_special_ext_pt")


class PluginA(Plugin):

    a = Any(contributes_to="magic_special_ext_pt")

    def _a_default(self):
        return ["a"]


class PluginB(Plugin):

    b = Any(contributes_to="magic_special_ext_pt")

    def _b_default(self):
        return ["b"]


class PluginC(Plugin):

    c = Any(contributes_to="magic_special_ext_pt")

    def _c_default(self):
        return ["c"]


class PluginD(Plugin):

    d = Any(contributes_to="magic_special_ext_pt")

    def _d_default(self):
        return ["d"]


class PluginE(Plugin):

    e = Any(contributes_to="magic_special_ext_pt")

    def _e_default(self):
        return ["e"]

class PluginF(Plugin):

    f = Any(contributes_to="magic_special_ext_pt")

    def _f_default(self):
        return ["f"]


class PluginG(Plugin):

    g = Any(contributes_to="magic_special_ext_pt")

    def _g_default(self):
        return ["g"]


class PluginH(Plugin):

    h = Any(contributes_to="magic_special_ext_pt")

    def _h_default(self):
        return ["h"]


class PluginI(Plugin):

    i = Any(contributes_to="magic_special_ext_pt")

    def _i_default(self):
        return ["i"]


class PluginJ(Plugin):

    j = Any(contributes_to="magic_special_ext_pt")

    def _j_default(self):
        return ["j"]


def main():
    application = Application(
        plugin_manager=PluginManager(
            plugins=[
                DefinesExtPt(),
                PluginA(),
                PluginB(),
                PluginC(),
                PluginD(),
                PluginE(),
                PluginF(),
                PluginG(),
                PluginH(),
                PluginI(),
                PluginJ(),
            ],
        )
    )

    def get_extensions_and_stop(event):
        application.get_extensions("magic_special_ext_pt")
        profile.disable()
        application.stop()

    application.observe(
        get_extensions_and_stop,
        "started"
    )

    application.start()

    profile.dump_stats(
        "C:\\Users\\rporuri\\work\\github\\ets\\envisage\\temp\\temp.prof"
    )


if __name__ == "__main__":
    main()
```

</details>

**Comment by rahulporuri** [comment]
The changes I propose are below, which I expect will improve the startup time

```

diff --git a/envisage/plugin.py b/envisage/plugin.py
index c2771c0..370baa0 100644
--- a/envisage/plugin.py
+++ b/envisage/plugin.py
@@ -16,7 +16,7 @@ import os
 from os.path import exists, join

 # Enthought library imports.
-from traits.api import Instance, List, Property, Str, provides
+from traits.api import Instance, List, Property, Set, Str, provides
 from traits.util.camel_case import camel_case_to_words

 # Local imports.
@@ -372,6 +372,8 @@ class Plugin(ExtensionProvider):

         return protocol

+    _extension_methods = Set(args=())
+
     def _harvest_methods(self, extension_point_id):
         """ Harvest all method-based contributions. """

@@ -379,10 +381,19 @@ class Plugin(ExtensionProvider):
         # Using inspect.getmembers(self) here will cause an infinite recursion,
         # so use an internal HasTraits method for inspecting the MRO of the
         # instance's type to find all methods instead.
-        for name in self._each_trait_method(self):
-            value = getattr(self, name)
-            if self._is_extension_method(value, extension_point_id):
-                result = value()
+        if len(self._extension_methods) == 0:
+            # We don't expect that methods which contribute to an extension
+            # point will be added dynamically.
+            for method_name in self._each_trait_method(self):
+                method = getattr(self, method_name)
+                if (inspect.ismethod(method)
+                    and getattr(method, "__extension_point__", None)
+                ):
+                    self._extension_methods.add(method)
+
+        for method in self._extension_methods:
+            if method.__extension_point__ == extension_point_id:
+                result = method()
                 if not isinstance(result, list):
```

**Comment by rahulporuri** [comment]
@aaronayres35 suggests another approach where instead of using `_each_trait_method`, we simply check methods defined on the class which inherits from the `Plugin` class - none of the other classes in the class heirarchy will have methods that contribute to an extension point.

**Comment by rahulporuri** [comment]
I don't fully understand the rationale behind adding `@contributes_to` in the first place. This was introduced in https://github.com/enthought/envisage/commit/7276552ae6c51c766b0efb501b5e05c11cd221be. That commit isn't associated with a PR so we don't get a better idea of the changes introduced but we do see this in the commit message 

>  - added a 'contributes_to' decorator for the common case when a plugin is not intending to dynamically change its contributions...

I don't fully understand that comment. We use traits with metadata `contributes_to` regularly in plugins which don't dynamically change contributions.

Note also that I used GitHub code search but I couldn't find a single user of this decorator - https://github.com/search?q=org%3Aenthought+%22contributes_to%22+extension%3Apy&type=Code.

On a related note, the `enthought.` extension point ID checks were added in https://github.com/enthought/envisage/commit/a6b4010e39e3a2584942d43f2e0b11224199cc52 - and again, its not clear why exactly these were done. But, from the looks of it, that too can be removed now.

**Comment by mdickinson** [comment]
I think we can kill the `contributes_to` decorator, especially if its existence is adding a time hit to all the Envisage-using projects, none of which actually use the decorator.

On process, we have various options, from most disruptive to least disruptive:

- Remove `contributes_to` in the next major release of Envisage (Envisage 6.0.0), without  a prior deprecation.
- Deprecate `contributes_to` in the next minor release, then remove in the following major release.
- Keep `contributes_to` but make the functionality to discover decorated methods "opt-in" (through a suitable flag somewhere), so that projects have to explicitly request it if they want it.
- Keep `contributes_to` but provide a way (e.g., a flag in the plugin manager) to allow projects to declare that they don't use it, so that they can opt out of the expensive checks.

Given that there's zero evidence of the `contributes_to` decorator actually being used in either internal Enthought projects or other open source projects, I'd go with the first option, possibly together with a warning message to the ets-users mailing list first.

**Comment by corranwebster** [comment]
> > * added a 'contributes_to' decorator for the common case when a plugin is not intending to dynamically change its contributions...
> 
> I don't fully understand that comment. We use traits with metadata `contributes_to` regularly in plugins which don't dynamically change contributions.

I think the idea is that in many cases the contribution never changes, so having a full-blown trait with associated listener infrastructure to track changes which will never occur is overkill.  The decorator was intended to give a "simpler" interface that supplies an unchanging value with less typing.

**Comment by corranwebster** [comment]
> On a related note, the `enthought.` extension point ID checks were added in [a6b4010](https://github.com/enthought/envisage/commit/a6b4010e39e3a2584942d43f2e0b11224199cc52) - and again, its not clear why exactly these were done. But, from the looks of it, that too can be removed now.

This was almost certainly because back in the old-times all of ETS lived in an `enthought.*` package namespace - we split out the packages a decade ago, but during the transition there was need for code that understood both package structures.

It can safely be removed.
