### ISSUE TITLE
Extension point resolution too eager in Envisage 6.0.0

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#417]
A project using Envisage 6.0.0 has encountered a serious regression: with Envisage 5.0.0 and earlier versions, when starting an Envisage-based application, all plugins were started before extension point contributions between plugins were resolved. With Envisage 6.0.0, some extension point contributions are resolved while plugins are starting. This means that a plugin that contributes to another extension point can no longer assume that it has already been started, and can no longer depend on traits that happen to be initialised by the `start` method.

(As a side note, initialising traits in the `start` method is something of an antipattern; that doesn't make this any less of a regression.)

The bug appears to have been introduced as a result of #354.

I don't yet have a shareable reproducing example, but I'm working on it.

**Comment by rahulporuri** [comment]
In the short term (this week), we'll revert #354 and push out a bugfix release.

**Comment by mdickinson** [comment]
Thanks, @rahulporuri. That should give us some breathing space to add new tests and figure out what the right approach is.

**Comment by rahulporuri** [comment]
@mdickinson in the meanwhile, it would be good to have a reproducible example, if you already have one.

**Comment by mdickinson** [comment]
Yep, I'll see if I can come up with a test. It's probably easier to create an example from scratch than to cut down the project-based example that I have.

**Comment by mchilvers** [comment]
I know this is a bit LTTP but lazy loading in envisage was not by accident...it is a fundamental design principle so messing this up is pretty scary.

**Comment by mdickinson** [comment]
Since the issue described here no longer exists, I'll close here. I've re-opened the original issue #291 that #354 attempted to solve.
