### ISSUE TITLE
No ets repo for 4.4.0?

### ISSUE THREAD

**Issue by opoplawski** [enthought/envisage#43]
I don't see envisage-4.4.0.tar.gz at http://www.enthought.com/repo/ets/

**Comment by mdickinson** [comment]
Closing as out of date; the ets repo is no longer maintained. Envisage tarballs can be found on PyPI, and eggs are available from `packages.enthought.com` via EDM (they can also be seen through the web interface at https://packages.enthought.com/ui/eggs).
