### ISSUE TITLE
Remove safeweakref

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#514]
For 7.0, let's remove the deprecated `safeweakref` helper.

xref: #271

**Comment by mdickinson** [comment]
@homosapien-lcy Would you be interested in taking a look at this one?

**Comment by homosapien-lcy** [comment]
Sure, will work on it

**Comment by homosapien-lcy** [comment]
After some searching, the old module that uses safeweakref now is test_safeweakref. So could we just delete safeweakref and test_safeweakref for this issue?

**Comment by mdickinson** [comment]
> So could we just delete safeweakref and test_safeweakref for this issue?

Yes, exactly.
