### ISSUE TITLE
IPythonKernelPlugin: Remove contributed menu action

### ISSUE THREAD

**Issue by pberkes** [enthought/envisage#55]
It leaves no option to an application developer to get the IPython kernel service and the `kernel_namespace` extension point, but start Qt consoles in some other way. Or even just change the location and name of the menu action.

Developers will need to contribute names to `kernel_namespace`, anyway, so they have to write some plugin code in any case.

**Comment by pberkes** [comment]
What do you think @dpinte ?

**Comment by dpinte** [comment]
@pberkes :+1:

**Comment by corranwebster** [comment]
+1 Kernel service should be separate from UI components.

**Comment by rahulporuri** [comment]
closing this issue as it was resolved in https://github.com/enthought/envisage/pull/57
