### ISSUE TITLE
IPythonKernelPlugin: remove qtconsole menu entries that do not work

### ISSUE THREAD

**Issue by pberkes** [enthought/envisage#56]
Some of the menu entries in the qtconsole that is opened by the IPythonKernelPlugin do not work. We should customize the available menus so that that does not happen.

This is the place where IPython creates the menus: https://github.com/ipython/ipython/blob/rel-3.2.1/IPython/qt/console/mainwindow.py#L344

**Comment by mdickinson** [comment]
Closing: IPython components have been removed from Envisage.
